name: Homarr
description:
  Homarr is a modern, lightweight dashboard homepage that provides a beautiful
  and customizable interface for organizing your self-hosted services and
  applications. It offers a clean, responsive design with support for widgets,
  bookmarks, and service monitoring. Homarr helps you create a centralized
  starting point for all your self-hosted applications with an intuitive and
  user-friendly interface.
instructions: null
changeLog:
  - date: 2025-10-07
    description: First Release
links:
  - label: GitHub
    url: https://github.com/homarr-labs/homarr
  - label: Documentation
    url: https://homarr.dev
  - label: Easypanel Documentation
    url: https://homarr.dev/docs/getting-started/installation/easy-panel
contributors:
  - name: Ahson Shaikh
    url: https://github.com/Ahson-Shaikh
schema:
  type: object
  required:
    - appServiceName
    - appServiceImage
    - timezone
  properties:
    appServiceName:
      type: string
      title: App Service Name
      default: homarr
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/homarr-labs/homarr:v1.40.0
    timezone:
      type: string
      title: Timezone
      description: Timezone for the application
      default: Australia/Melbourne
benefits:
  - title: Centralized Dashboard
    description:
      Create a single, unified dashboard that serves as the starting point for
      all your self-hosted services and applications, eliminating the need to
      remember multiple URLs and bookmarks.
  - title: Customizable Interface
    description:
      Highly customizable interface with drag-and-drop widgets, customizable
      themes, and flexible layout options to match your personal preferences and
      workflow.
  - title: Service Monitoring
    description:
      Built-in service monitoring capabilities with status indicators and health
      checks to quickly identify which services are running and accessible.
  - title: Responsive Design
    description:
      Fully responsive design that works seamlessly across desktop, tablet, and
      mobile devices, providing consistent access to your services from
      anywhere.
features:
  - title: Widget System
    description:
      Comprehensive widget system with support for various widgets including
      weather, system information, service status, and custom integrations for
      enhanced functionality.
  - title: Bookmark Management
    description:
      Organize and categorize your bookmarks with support for custom icons,
      descriptions, and grouping to create a personalized navigation experience.
  - title: Theme Customization
    description:
      Multiple built-in themes with customizable colors, fonts, and layouts to
      create a personalized dashboard that matches your aesthetic preferences.
  - title: Service Integration
    description:
      Easy integration with popular self-hosted services including Plex, Sonarr,
      Radarr, and many others with automatic service discovery and status
      monitoring.
  - title: Search Functionality
    description:
      Built-in search functionality to quickly find and access your bookmarked
      services and applications across your entire dashboard.
  - title: Data Persistence
    description:
      All dashboard configurations, bookmarks, and customizations persist across
      container restarts and updates with encrypted local storage.
  - title: Multi-User Support
    description:
      Support for multiple user accounts with individual dashboard
      configurations and preferences for team or family use.
  - title: API Integration
    description:
      RESTful API support for programmatic access and integration with other
      applications and automation tools.
tags:
  - Dashboard
  - Homepage
  - Self-hosted
  - Widgets
  - Bookmarks
  - Monitoring
  - Customizable
  - Web App
