name: Homarr
description:
  Homarr is a powerful dashboard designed to simplify the management of your
  server. It provides a sleek, modern interface that brings all your apps and
  services together in one place, allowing you to access and control everything
  with ease. Homarr seamlessly integrates with the apps you've added, offering
  valuable insights and complete control. You can add your self-hosted
  applications or favorite websites to your dashboard and organize them as you
  like. Homarr supports integration with many popular applications to enhance
  your user experience. It is customizable, accessible, and supports 23
  languages. With Homarr, you can control and monitor your network directly, use
  integrations to display data and control apps, and even create your own
  dashboard using a comprehensible and easy-to-use visual editor. Homarr is
  open-source and allows commercial usage. It features a quick search function
  to easily navigate through your apps and supported integrations.
instructions: null
changeLog:
  - date: 2025-10-07
    description: First Release
links:
  - label: GitHub
    url: https://github.com/homarr-labs/homarr
  - label: Documentation
    url: https://homarr.dev
  - label: Easypanel Documentation
    url: https://homarr.dev/docs/getting-started/installation/easy-panel
contributors:
  - name: Ahson Shaikh
    url: https://github.com/Ahson-Shaikh
schema:
  type: object
  required:
    - appServiceName
    - appServiceImage
    - timezone
  properties:
    appServiceName:
      type: string
      title: App Service Name
      default: homarr
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/homarr-labs/homarr:v1.40.0
    timezone:
      type: string
      title: Timezone
      description: Timezone for the application
      default: Australia/Melbourne
benefits:
  - title: Centralized Dashboard
    description:
      Create a single, unified dashboard that serves as the starting point for
      all your self-hosted services and applications, eliminating the need to
      remember multiple URLs and bookmarks.
  - title: Customizable Interface
    description:
      Highly customizable interface with drag-and-drop widgets, customizable
      themes, and flexible layout options to match your personal preferences and
      workflow.
  - title: Service Monitoring
    description:
      Built-in service monitoring capabilities with status indicators and health
      checks to quickly identify which services are running and accessible.
  - title: Responsive Design
    description:
      Fully responsive design that works seamlessly across desktop, tablet, and
      mobile devices, providing consistent access to your services from
      anywhere.
features:
  - title: Widget System
    description:
      Comprehensive widget system with support for various widgets including
      weather, system information, service status, and custom integrations for
      enhanced functionality.
  - title: Bookmark Management
    description:
      Organize and categorize your bookmarks with support for custom icons,
      descriptions, and grouping to create a personalized navigation experience.
  - title: Theme Customization
    description:
      Multiple built-in themes with customizable colors, fonts, and layouts to
      create a personalized dashboard that matches your aesthetic preferences.
  - title: Service Integration
    description:
      Easy integration with popular self-hosted services including Plex, Sonarr,
      Radarr, and many others with automatic service discovery and status
      monitoring.
  - title: Search Functionality
    description:
      Built-in search functionality to quickly find and access your bookmarked
      services and applications across your entire dashboard.
  - title: Data Persistence
    description:
      All dashboard configurations, bookmarks, and customizations persist across
      container restarts and updates with encrypted local storage.
  - title: Multi-User Support
    description:
      Support for multiple user accounts with individual dashboard
      configurations and preferences for team or family use.
  - title: API Integration
    description:
      RESTful API support for programmatic access and integration with other
      applications and automation tools.
tags:
  - Dashboard
  - Homepage
  - Self-hosted
  - Widgets
  - Bookmarks
  - Monitoring
  - Customizable
  - Web App
