name: Airsonic
description:
  Airsonic is a free, web-based media streamer providing ubiquitous access to
  your music. Use it to share your music with friends, or to listen to your own
  music while at work. You can stream to multiple players simultaneously, for
  instance to one player in your kitchen and another in your living room. It
  supports very large music collections and works with any audio or video format
  that can stream over HTTP.
instructions: null
changeLog:
  - date: 2025-09-29
    description: First release
links:
  - label: GitHub
    url: https://github.com/airsonic/airsonic
  - label: Documentation
    url: https://airsonic.github.io/docs/
  - label: DockerHub
    url: https://hub.docker.com/r/airsonic/airsonic
contributors:
  - name: Ahson Shaikh
    url: https://github.com/Ahson-Shaikh
schema:
  type: object
  required:
    - appServiceName
    - appServiceImage
  properties:
    appServiceName:
      type: string
      title: App Service Name
      default: airsonic
    appServiceImage:
      type: string
      title: App Service Image
      default: airsonic/airsonic:10.6.2-RELEASE
benefits:
  - title: Music Streaming
    description:
      Stream your music collection to any device with a web browser, supporting
      multiple simultaneous streams and transcoding for optimal playback.
  - title: Multi-Format Support
    description:
      Supports virtually any audio or video format that can stream over HTTP,
      including MP3, AAC, OGG, WMA, FLAC, APE, Musepack, WavPack and more.
  - title: Large Collection Support
    description:
      Designed to handle very large music collections (hundreds of gigabytes)
      with efficient indexing and browsing capabilities.
  - title: Self-Hosted
    description:
      Complete control over your music library with no external dependencies or
      data sharing with third parties.
features:
  - title: Web Interface
    description:
      Clean, responsive web interface accessible from any device with a browser.
  - title: Podcast Support
    description:
      Integrated podcast receiver with features similar to iTunes, including
      OPML export capabilities.
  - title: Multiple Players
    description:
      Stream to multiple players simultaneously for different rooms or users.
  - title: Transcoding
    description:
      Automatic transcoding to different formats and bitrates for optimal
      streaming.
  - title: User Management
    description:
      Multi-user support with individual playlists, preferences, and access
      controls.
  - title: Mobile Apps
    description:
      Compatible with various mobile apps for iOS and Android devices.
  - title: DLNA Support
    description: Built-in DLNA server for streaming to compatible devices.
  - title: Data Persistence
    description:
      All music metadata, playlists, and user data persists across container
      restarts.
tags:
  - Music Streaming
  - Media Server
  - Self-hosted
  - Audio
  - Video
  - Podcast
  - DLNA
  - Web Interface
